feat: Greetings.yml added
tushar5526/sarthi pull request #34
Opened 2024-01-31 04:30 UTC by praptisharma28

closes #33

2024-01-31 05:07 UTC, tushar5526 commented
@praptisharma28 you will have to install pre-commit `pip install pre-commit` and `pre-commit install` and then run pre-commit on all files to fix the error. `pre-commit run --all-files`

2024-01-31 05:42 UTC, praptisharma28 commented
Added precomit in the environment variables , still its not recognised ? @tushar5526

2024-01-31 13:31 UTC, tushar5526 commented
https://pre-commit.com/ - Setup this

2024-01-31 14:28 UTC, praptisharma28 commented
done @tushar5526

2024-02-01 05:04 UTC, tushar5526 commented on requirements.txt
> +pre-commit
pre-commit will rather go in `requirements-dev.txt` as it is a dev requirement not a core requirement.

2024-02-01 05:04 UTC, tushar5526 requested changes
Move pre-commit to dev requirements.

2024-02-01 09:55 UTC, praptisharma28 commented
ok done @tushar5526 , dev already have a version of pre-commit. removed from requirements.txt . You can check now.

2024-02-01 16:57 UTC, praptisharma28 commented
@tushar5526 do I need to do anything more?

2024-02-01 17:42 UTC, merged